In [8]:
import numpy as np
import time

Hospital Patient Flow & Care Analytics
You are a data analyst at a hospital. Management wants insights on:

patient volume (daily/weekly)

waiting times and length of stay

readmissions

department performance

identifying risk/high-priority cases

Dataset A Patient records (rows = patients)

Columns description:


Age

Department code (0=Emergency, 1=Outpatient, 2=Surgery, 3=Pediatrics)

Severity score (1–5)

Waiting time (minutes)

Length of stay (hours)

Readmitted within 30 days? (0=No, 1=Yes)

Treatment cost



In [9]:
departments = np.array(["Emergency", "Outpatient", "Surgery", "Pediatrics"])

In [10]:
patients = np.array([
    [25, 0, 4, 60, 10, 0, 350],
    [60, 2, 5, 30, 48, 1, 4200],
    [40, 1, 2, 20,  2, 0, 150],
    [10, 3, 3, 15,  6, 0, 200],
    [72, 0, 5, 90, 24, 1, 1800],
    [33, 1, 1, 10,  1, 0, 80],
    [55, 2, 4, 45, 36, 0, 3500],
    [28, 0, 3, 50,  8, 0, 500],
    [65, 2, 5, 25, 72, 1, 9000],
    [18, 3, 2, 12,  3, 0, 120],
    [49, 1, 3, 35,  4, 0, 220],
    [80, 0, 4, 110, 30, 1, 2500],
])

days = np.array(["Mon","Tue","Wed","Thu","Fri","Sat","Sun"])

daily_visits = np.array([
    [30, 50, 10, 20],
    [35, 55, 12, 18],
    [40, 60, 15, 22],
    [38, 58, 14, 25],
    [45, 65, 18, 30],
    [50, 40, 20, 15],
    [55, 35, 22, 10],
])

Part 1 — Patient Summary KPIs
Total number of patients in the patients dataset.
Average age of patients.
Average waiting time (minutes).
Average length of stay (hours).
Total treatment cost for all patients.
Part 2 — Weekly Flow (Daily visits table)
Total visits in the week (all departments combined).
Total visits per department for the week.
Which day had the highest total visits?
Which department had the highest visits on Saturday?
Part 3 — Department Performance (Patients table)
Count how many patients are in each department (Emergency/Outpatient/Surgery/Pediatrics).
Compute average waiting time per department.
Compute average cost per department.
Which department has the highest average waiting time?

PART 1

In [11]:

patients.shape[0]
# Number of patients is equal to number of rows

12

In [12]:
# no 2
age = np.array([25,60,40,10,72,33,55,28,65,18,49,80])
print(f"The average age is:{np.average(age)}")

The average age is:44.583333333333336


In [13]:
# no 3
waiting_time = np.array([60,30,20,15,90,10,45,50,25,12,35,110])
print(f"The average waiting time is:{np.average(waiting_time)}")

The average waiting time is:41.833333333333336


In [14]:
# no 4
length_of_stay=np.array([10,48,2,6,24,1,36,8,72,3,4,30])
print(f"The average length_of_stay is:{np.average(length_of_stay)}")

The average length_of_stay is:20.333333333333332


In [15]:
# no 5 Total treatment cost for all pateints
treatment_cost = np.array([350,4200,150,200,1800,80,3500,500,9000,120,220,2500])
print(f"The total for treatment cost is :{np.sum(treatment_cost)}")

The total for treatment cost is :22620


PART 2

In [16]:
# no 1
print(f"Total visits in the week is :{np.sum(daily_visits)}")

Total visits in the week is :907


In [17]:
# no 2
print(f"Visits per department for the week is :{np.sum(daily_visits,axis=0)}")

Visits per department for the week is :[293 363 111 140]


In [18]:
# no 3
visit_for_each_day = np.sum(daily_visits,axis=1)
print(visit_for_each_day)
max_visits = np.max(visit_for_each_day)
print(max_visits) # 158 = Friday

[110 120 137 135 158 125 122]
158


In [19]:
# no 4
saturday_Visits = daily_visits[5]
print(saturday_Visits)
max_depart_visit = max(saturday_Visits)
print(f"The maximum vist on saturday is :{max_depart_visit}")

[50 40 20 15]
The maximum vist on saturday is :50


PART 3

In [65]:
# no 1
department_code = patients[:,1]
num = np.bincount(department_code)
print(num)
print("Emergency:",4)
print("Outpatient:",3)
print("Surgery:",3)
print("Pediatrics:",2)

[4 3 3 2]
Emergency: 4
Outpatient: 3
Surgery: 3
Pediatrics: 2


In [61]:
# no 2
# Average waiting time per department
emergency = np.array([60,90,50,110])
wait_time = np.average(emergency)
print(f"The average waiting time per for emergency is {wait_time}")
outpatient = np.array([20,10,35])
average_outpatient = np.average(outpatient)
print(f"The average waiting time for outpatient is {average_outpatient}")
surgery = np.array([30,45,25])
average_surgery = np.average(surgery)
print(f"The average waiting time for surgery is {average_surgery}")
pediatrics = np.array([15,12])
average_pediatrics = np.average(pediatrics)
print(f"The average waiting time for pediatrics is {average_pediatrics}")

The average waiting time per for emergency is 77.5
The average waiting time for outpatient is 21.666666666666668
The average waiting time for surgery is 33.333333333333336
The average waiting time for pediatrics is 13.5


In [62]:
# no 3
emergency = np.array([350,1800,500,2500])
print(f"The average cost for emergency is {np.average(emergency)}")
outpatient = np.array([150,80,220])
print(f"The average cost for outpatient is {np.average(outpatient)}")
surgery = np.array([4200,3500,9000])
print(f"The average cost for surgery is {np.average(surgery)}")
pediatrics = np.array([200,120])
print(f"The average cost for pediatrics is {np.average(pediatrics)}")

The average cost for emergency is 1287.5
The average cost for outpatient is 150.0
The average cost for surgery is 5566.666666666667
The average cost for pediatrics is 160.0


In [58]:
# no 4 Department with the highest waiting time
average_waiting_time_per_department = np.array([77.5,21.666666666666668,33.333333333333336,13.5])
print(f"The highest averege waiting time is {max(average_waiting_time_per_department)}")


The highest averege waiting time is 77.5
